### ISSUE TITLE
Unable to update user model when using email login

### ISSUE THREAD

**Issue by rdofl** [ziptofaf/gdpr-rails#3]
Hi,

I've been using the code in the email-login branch and can successfully log in and out using an encrypted email. However, when it comes to update fields in the user model I get this error:

ActiveRecord::RecordInvalid (Validation failed: Email has already been taken)

From what I understand the email is getting hashed before save and then validated with validate_email_uniqueness to make sure it's unique in the db. This works for a new user but when updating the record for an existing user, the validation will fail as email_unique? returns false (as the user already exists).

I've tried adding  if: :email_changed? to validate :validate_email_uniqueness to see if that works but I'm still getting the validation error.

Any thoughts where I could be going wrong? Many Thanks,

**Comment by ziptofaf** [comment]
Branch email-login I assume (this really should not be happening in the master)? I think I fixed it, needed to add an id check so it doesn't compare against itself.

**Comment by rdofl** [comment]
That works! thank you very much for the quick fix!
